# Your recipe starts here.
# For more information, check out https://blue-build.org/reference/recipe/

name: my-aurora-t480
description: A custom Aurora image for my Lenovo T480 with specific hardware fixes and tools.

# The base image to build on top of.
# I've assumed you are using the default GNOME version of Aurora.
# If you use the KDE version, change this to "aurora-kde".
base: ghcr.io/aurora-os/aurora-gnome
from: latest # This will use the latest version of the Aurora base image.

modules:
  - type: rpm-ostree
    repos:
      # Add the RPM Fusion repositories for multimedia codecs and other software.
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

    install:
      - distrobox       # Run other Linux distributions in a container
      - fish            # A user-friendly command line shell
      - zsh             # Another powerful command line shell

      # -- Lenovo T480/s Specific Fixes --
      - tlp             # Advanced power management
      - tlp-rdw         # TLP's radio device wizard
      - throttled       # To prevent CPU thermal throttling
      - zcfan           # Advanced fan control daemon
      - python3-validity # For the fingerprint reader

      # -- Multimedia Codecs from RPM Fusion --
      - gstreamer1-plugins-bad-free-extras
      - gstreamer1-plugins-ugly
      - gstreamer1-vaapi
      - intel-media-driver # Hardware video acceleration for Intel GPUs

    # You can remove packages from the base image here if you don't want them.
    # We are not removing any for now.
    remove:
      # - firefox
      # - firefox-langpacks

  # This module enables the automatic signing of your image.
  - type: signing
